version: '3.1'
services:
  voicevox:
    image: voicevox/voicevox_engine:latest
    restart: always
    ports:
      - "50021:50021"
    volumes:
      - ./docker/volumes/voicevox:/opt/voicevox_engine/.voicevox_engine
